1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


3. Create a null vector of size 10 (★☆☆)

In [3]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)
 

In [4]:
a.size

10

5. How to get the documentation of the numpy add function from the command line? (★☆☆)

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
 

In [6]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)
 

In [9]:
a=np.arange(10,50)
a=a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a=[1,2,0,0,4,0]
a=np.nonzero(a)
a

(array([0, 1, 4], dtype=int64),)

11. Create a 3x3 identity matrix (★☆☆)
 

In [12]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
a=np.random.random((3,3,3))
a

array([[[0.66034504, 0.56707534, 0.37995666],
        [0.50079473, 0.03609322, 0.76073188],
        [0.13830363, 0.51786281, 0.36837359]],

       [[0.33805672, 0.41990977, 0.8357216 ],
        [0.67319568, 0.55119923, 0.19594283],
        [0.76707418, 0.73470316, 0.16004181]],

       [[0.4244481 , 0.15088901, 0.90241957],
        [0.44034023, 0.30857191, 0.73404774],
        [0.95084451, 0.68995772, 0.23671481]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
a=np.random.random((10,10))
print(a)


[[0.87895821 0.80653436 0.83630177 0.27642332 0.68577637 0.34456368
  0.70125826 0.75513492 0.45479431 0.23003377]
 [0.17905277 0.14341443 0.6694635  0.91713636 0.31629145 0.43278225
  0.17267194 0.72948219 0.96628284 0.8136298 ]
 [0.75608642 0.37450456 0.03622497 0.6478653  0.06092802 0.00567927
  0.15418493 0.15889776 0.17264487 0.18527717]
 [0.33768177 0.64482025 0.50025705 0.17416484 0.77078342 0.76004237
  0.64632441 0.24606175 0.73004645 0.10664271]
 [0.58070827 0.87264256 0.65833254 0.3896965  0.72505897 0.57785713
  0.44734077 0.54160692 0.72081991 0.70202208]
 [0.47826196 0.77069122 0.52266059 0.99469564 0.68182858 0.3868966
  0.68168305 0.11546578 0.05989374 0.30615066]
 [0.65123565 0.25400839 0.65484095 0.26441891 0.6976215  0.17951261
  0.64335988 0.99324559 0.41253038 0.12995642]
 [0.0225308  0.79140125 0.25601373 0.52446333 0.47662252 0.08376035
  0.87419469 0.07406872 0.7392426  0.03098946]
 [0.86776299 0.22349959 0.33947664 0.19189533 0.3228157  0.30018945
  0.44115458 

In [28]:
print(a.min(axis=0))


[0.0225308  0.14341443 0.03622497 0.17416484 0.06092802 0.00567927
 0.15418493 0.07406872 0.05989374 0.03098946]


In [29]:
print(a.max(axis=0))

[0.87895821 0.87264256 0.83630177 0.99469564 0.77078342 0.76004237
 0.87419469 0.99324559 0.96628284 0.8136298 ]


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [35]:
a=np.random.random((30))
a=a.mean()
a

0.5119474463107578

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [41]:
a=np.ones((4,4))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [49]:
a=np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

17. What is the result of the following expression? (★☆☆)

In [51]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

19. Multiply a 5x3 matrix by a 3x2 matrix (★☆☆)

In [ ]:
 20.Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [31]:
a = np.arange(20)
a[(3 < a) & (a < 8)] *=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


21. What is the output of the following script? (★☆☆)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [32]:
print(sum(range(5),-1)) 
from numpy import * 
print(sum(range(5),-1))

9
10


22.Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


2 << Z >> 2 


Z <- Z 

23.What are the result of the following expressions? (★☆☆)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)

In [34]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Asus\AppData\Local\Temp/ipykernel_13232/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Asus\AppData\Local\Temp/ipykernel_13232/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


24.How to round away from zero a float array ? (★☆☆)

In [39]:
a=np.random.uniform((-5,+10,20))
print(a)
a=np.where(a>0,np.ceil(a),np.floor(a))
print(a)

[-1.63195024  4.97113487 18.71343617]
[-2.  5. 19.]


25.How to find common values between two arrays? (★☆☆)


In [42]:
#we can find common values between two arrays with the help intersect1d().
a1 = np.array([0, 1, 2, 3, 4])
a2 = np.array([1, 2, 3, 4, 5])
print(np.intersect1d(a1, a2))

[1 2 3 4]


26. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [43]:

print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\Asus\AppData\Local\Temp/ipykernel_13232/1923599356.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


27.How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [49]:

today=np.datetime64('2022-10-12')
yesterday= today - np.timedelta64(1)
print(yesterday)
print(today)
tommorow=today+np.timedelta64(1)
print(tommorow)

2022-10-11
2022-10-12
2022-10-13


28.How to get all the dates corresponding to the month of July 2016? (★★☆)

In [53]:
a=np.arange(datetime64('2022-07-01'),datetime64('2022-07-31'))
a

array(['2022-07-01', '2022-07-02', '2022-07-03', '2022-07-04',
       '2022-07-05', '2022-07-06', '2022-07-07', '2022-07-08',
       '2022-07-09', '2022-07-10', '2022-07-11', '2022-07-12',
       '2022-07-13', '2022-07-14', '2022-07-15', '2022-07-16',
       '2022-07-17', '2022-07-18', '2022-07-19', '2022-07-20',
       '2022-07-21', '2022-07-22', '2022-07-23', '2022-07-24',
       '2022-07-25', '2022-07-26', '2022-07-27', '2022-07-28',
       '2022-07-29', '2022-07-30'], dtype='datetime64[D]')

29. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
 

In [64]:
np.tile(np.arange(0,5),(5,1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

30.Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [65]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

31.Create a random vector of size 10 and sort it (★★☆)

In [67]:
a=np.random.random(10)
print(np.sort(a))


[0.09780995 0.26044635 0.26304486 0.37552686 0.42045483 0.44079013
 0.55363935 0.60999853 0.65849603 0.77760698]


32.How to sum a small array faster than np.sum? (★★☆)

In [68]:
a = np.arange(1,5)
np.add.reduce(a)

10

33.Consider two random array A and B, check if they are equal (★★☆)

In [71]:
a=np.random.random(5)
print(a)
b=np.random.random(5)
print(b)
np.array_equal(a,b)

[0.59045428 0.7426275  0.01254787 0.01039353 0.39663273]
[0.55040807 0.03986025 0.62458977 0.70452432 0.80179614]


False

34.Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [76]:
a=np.random.random(10)
a[np.argmax(a)]=0
print(a)

[0.68048089 0.61229272 0.49257882 0.         0.14910303 0.61538516
 0.04907993 0.10783987 0.15296295 0.35778778]


35.How to print all the values of an array? (★★☆)
 

In [82]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


36.Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [88]:
t=[('x','f8'),('y','f8'),('r','f8'),('g','f8'),('b','f8')]
array= np.zeros((4,), dtype=t)
array

array([(0., 0., 0., 0., 0.), (0., 0., 0., 0., 0.), (0., 0., 0., 0., 0.),
       (0., 0., 0., 0., 0.)],
      dtype=[('x', '<f8'), ('y', '<f8'), ('r', '<f8'), ('g', '<f8'), ('b', '<f8')])

37.How to convert a float (32 bits) array into an integer (32 bits) in place?

In [91]:
a=np.random.random(5).astype(np.float32)
print(a)
print(np.int32(a))

[0.7059268  0.5411409  0.35555077 0.4270274  0.2487304 ]
[0 0 0 0 0]


38.Subtract the mean of each row of a matrix (★★☆)

In [96]:
a=np.random.random((30))
print(a)
print("-----------------------------------------------------")
a=a-a.mean()
print(a)

[0.58656148 0.29210974 0.41249175 0.36388448 0.19029885 0.39286287
 0.47232139 0.50568332 0.11339725 0.76562685 0.54162999 0.78507959
 0.76793278 0.0343551  0.37363289 0.88180001 0.42283312 0.18392781
 0.64401033 0.85145928 0.3784053  0.73603692 0.64779461 0.27291752
 0.47339976 0.74753158 0.02566488 0.08493609 0.34837143 0.64218389]
-----------------------------------------------------
[ 0.12192345 -0.17252829 -0.05214628 -0.10075355 -0.27433918 -0.07177516
  0.00768336  0.04104529 -0.35124078  0.30098882  0.07699196  0.32044157
  0.30329475 -0.43028293 -0.09100514  0.41716198 -0.04180491 -0.28071022
  0.17937231  0.38682125 -0.08623273  0.27139889  0.18315658 -0.19172051
  0.00876173  0.28289355 -0.43897315 -0.37970194 -0.1162666   0.17754586]


39.How to sort an array by the nth column? (★★☆)

In [111]:
a=np.random.random((3,4))
print(a)
print("---------------------------------------------------------")
a=a[a[:,2].argsort()]
print(a)

[[0.03319543 0.03550945 0.95403518 0.71628829]
 [0.45660167 0.1944746  0.69316732 0.75884816]
 [0.34141136 0.58059802 0.18458977 0.37264211]]
---------------------------------------------------------
[[0.34141136 0.58059802 0.18458977 0.37264211]
 [0.45660167 0.1944746  0.69316732 0.75884816]
 [0.03319543 0.03550945 0.95403518 0.71628829]]


40.How to tell if a given 2D array has null columns? (★★☆)

In [114]:
a=np.random.random((3,4))
print(a)
a=a.any(axis=0).any()
print(a)

[[0.30117569 0.82223328 0.15773083 0.18924318]
 [0.47761114 0.39440088 0.11116715 0.2639816 ]
 [0.87688402 0.94984902 0.65364862 0.61779876]]
True


41.Find the nearest value from a given value in an array (★★☆)

In [115]:
a=np.random.random((3,4))
b=1
a=a.flat[np.abs(a-b).argmin()]
print(a)

0.8874796960972698


42. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [117]:
a=np.random.random((3,4))
print(a)
print("----------------------------------------------------")
a=a+1
print(a)

[[0.15903247 0.73079541 0.61685985 0.58631921]
 [0.04879246 0.74152749 0.06831738 0.74642379]
 [0.99007788 0.94093376 0.43967518 0.93882239]]
----------------------------------------------------
[[1.15903247 1.73079541 1.61685985 1.58631921]
 [1.04879246 1.74152749 1.06831738 1.74642379]
 [1.99007788 1.94093376 1.43967518 1.93882239]]


43.Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [124]:
a=np.random.random((4,4))
print(a)
print("---------------------------------------------------")
a=a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(a)

[[0.18994378 0.39501406 0.72631033 0.03195177]
 [0.05923355 0.44484858 0.34904475 0.87208951]
 [0.98394663 0.92266435 0.68202218 0.95746364]
 [0.51834025 0.06338577 0.29226477 0.42666298]]
---------------------------------------------------
7.915186909351133


44.How to get the diagonal of a dot product? (★★★)

In [127]:
a=np.random.random((3,3))
print(a)
print("-------------------------------------")
b=np.random.random((3,3))
print(b)
print("---------------------------------------")
c=np.diag(np.dot(a,b))
print(c)


[[0.92922408 0.71204841 0.07302228]
 [0.95468681 0.87119891 0.96756974]
 [0.11857297 0.33157283 0.9755987 ]]
-------------------------------------
[[0.61437621 0.66915873 0.26131381]
 [0.46776907 0.41681744 0.14028455]
 [0.39128307 0.12106107 0.79932294]]
---------------------------------------
[0.93253977 1.11910293 0.85731772]


45.How to swap two rows of an array? (★★★)

In [130]:
a=np.random.random((3,3))
print(a)
print("-------------------------------------")
a[[0,1]]=a[[1,0]]
print(a)

[[0.7533652  0.18743769 0.23351574]
 [0.51887    0.35380824 0.5832234 ]
 [0.24041405 0.0517159  0.09079448]]
-------------------------------------
[[0.51887    0.35380824 0.5832234 ]
 [0.7533652  0.18743769 0.23351574]
 [0.24041405 0.0517159  0.09079448]]


46.How to find the most frequent value in an array?

In [134]:
a= np.random.randint(0,15,50)
print (a)
print("------------------------------------------")
a=np.bincount(a).argmax()
print(a)

[ 8 13  8  1  3 11  5  0 11 12  7  4 12  9  6 12  5  1 12  2 12  7 13  1
 11  9  2  1  2  9 13 11 12 14  1 13  5 10  5 10  6 10 10  7  6  5  5 14
 13  0]
------------------------------------------
5


47.Compute a matrix rank (★★★)

In [135]:
from numpy.linalg import matrix_rank
print(np.eye(5))
print("-------------------------------------")
matrix_rank(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-------------------------------------


5

48.Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [142]:
a=np.arange(1,15,dtype=int)
print(a)
print("---------------------------------------------")
a=np.lib.stride_tricks.as_strided(a,(11,4),(4,4))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
---------------------------------------------
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


49. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [146]:
a=np.ones((16,16))
print(a)
print("-------------------------------------------------------------")
a=np.add.reduce(a).reshape(4,4)
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
-------------------------------------------------------------
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


50.How to get the n largest values of an array (★★★)

In [153]:
a=np.arange(100)
print(a)
print("-------------------------------------------------------------")
n=3
a=a[-n:]
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
-------------------------------------------------------------
[97 98 99]


51.How to create a record array from a regular array? (★★★)

In [159]:
a=np.array([("Bushra",8),("priya",8)])
print(a)
print("-----------------------------------------")
a=np.core.records.fromarrays(a.T,
                    
names='col1,col2',
formats='S8,i8')
print(a)

[['Bushra' '8']
 ['priya' '8']]
-----------------------------------------
[(b'Bushra', 8) (b'priya', 8)]


52.Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [160]:
a = np.random.rand(int(5e7))

%timeit np.power(a,3)
%timeit a*a*a
%timeit np.einsum('i,i,i->i',a,a,a)

3.44 s ± 126 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
587 ms ± 105 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
357 ms ± 36.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


53.Make an array immutable (read-only) (★★☆)

In [161]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

54.Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [164]:
a= np.random.random((10,2))
x=a[:,0]
y=a[:,1]
s=np.sqrt(x**2+y**2)
print(s)
k=np.arctan2(y,x)
print(k)

[0.52024631 0.41184723 0.53077488 1.24560387 0.91132645 0.18008298
 0.94729519 0.78614367 0.72674034 0.76087412]
[0.11027067 1.55454981 1.06215885 0.84880769 0.49987853 0.37325067
 0.42055357 0.79039873 1.35598494 0.99323025]


55.Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [168]:
a = np.zeros((10,10), [('x',float),('y',float)])
a['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(a)

[[(0.        , 0.) (0.11111111, 0.) (0.22222222, 0.) (0.33333333, 0.)
  (0.44444444, 0.) (0.55555556, 0.) (0.66666667, 0.) (0.77777778, 0.)
  (0.88888889, 0.) (1.        , 0.)]
 [(0.        , 0.) (0.11111111, 0.) (0.22222222, 0.) (0.33333333, 0.)
  (0.44444444, 0.) (0.55555556, 0.) (0.66666667, 0.) (0.77777778, 0.)
  (0.88888889, 0.) (1.        , 0.)]
 [(0.        , 0.) (0.11111111, 0.) (0.22222222, 0.) (0.33333333, 0.)
  (0.44444444, 0.) (0.55555556, 0.) (0.66666667, 0.) (0.77777778, 0.)
  (0.88888889, 0.) (1.        , 0.)]
 [(0.        , 0.) (0.11111111, 0.) (0.22222222, 0.) (0.33333333, 0.)
  (0.44444444, 0.) (0.55555556, 0.) (0.66666667, 0.) (0.77777778, 0.)
  (0.88888889, 0.) (1.        , 0.)]
 [(0.        , 0.) (0.11111111, 0.) (0.22222222, 0.) (0.33333333, 0.)
  (0.44444444, 0.) (0.55555556, 0.) (0.66666667, 0.) (0.77777778, 0.)
  (0.88888889, 0.) (1.        , 0.)]
 [(0.        , 0.) (0.11111111, 0.) (0.22222222, 0.) (0.33333333, 0.)
  (0.44444444, 0.) (0.55555556, 0.) (0.666666

56.Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [169]:
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C)

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_13232/1660820447.py, line 4)

57.Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [171]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


58.How to find the closest value (to a given scalar) in a vector? (★★☆)

In [175]:
a=np.arange(100)
print(a)
print("-----------------------------------")
b=np.random.uniform(0,100)
print(b)
print("------------------------------------")
c=(np.abs(a-b)).argmin()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
-----------------------------------
41.18540804446447
------------------------------------
41


59.How to tell if a given 2D array has null columns? (★★☆)

In [178]:
a=np.random.randint(0,3,(3,20))
print((a.any(axis=0)).any())

True


60.How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [179]:
X = [1,2,3,4,5,6]
I = [1,8,7,3,4,9]
F = np.bincount(I,X)
print(F)

[0. 1. 0. 4. 5. 0. 0. 3. 2. 6.]
